<a href="https://colab.research.google.com/github/Yatz1403/Pytorch_tutorials/blob/main/Pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##TENSORS

In [1]:
import torch
import numpy as np

In [2]:
d = [[1,2],[3,4]]
tensor1 = torch.tensor(d)

In [3]:
tensor1

tensor([[1, 2],
        [3, 4]])

In [9]:
tensor1.dtype

torch.int64

In [16]:
numpy_array = np.array(d)
tensor2 = torch.tensor(numpy_array)
tensor2

tensor([[1, 2],
        [3, 4]])

In [14]:
tensor3 = torch.randn(2,4)
tensor3

tensor([[ 0.5307,  1.7583,  0.1072,  0.1737],
        [ 1.0814,  0.4848,  0.7593, -0.0936]])