<a href="https://colab.research.google.com/github/Yatz1403/Pytorch_tutorials/blob/main/TensorMathOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [5]:
tens1 = torch.tensor([1,2,3,4])
tens2 = torch.tensor([5,6,7,8])


In [12]:
#add
#tens1+tens2
torch.add(tens1, tens2)

tensor([ 6,  8, 10, 12])

In [11]:
#sub
#tens2 - tens1
torch.sub(tens2, tens1)

tensor([4, 4, 4, 4])

In [10]:
#mul
#tens1*tens2
torch.mul(tens1,tens2)

tensor([ 5, 12, 21, 32])

In [16]:
#division
torch.div(tens1, tens2)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [18]:
#power
#tens1**tens2
torch.pow(tens1, tens2)

tensor([    1,    64,  2187, 65536])