<a href="https://colab.research.google.com/github/Yatz1403/Pytorch_tutorials/blob/main/TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensor operations


In [2]:
import torch

In [3]:
tensor1 = torch.arange(10)
tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Reshape(#number of sub arrays, # number of elements in the sub array)

In [9]:
tensor2 = tensor1.reshape(5,-1)
tensor2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [10]:
tensor3 = tensor1.reshape(-1,2)
tensor3

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

##slicing

In [12]:
tens = torch.arange(10)
tens

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
tens[4]

tensor(4)

In [17]:
tens2 = tens.reshape(-1,2)
tens2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
tens2[:,1]

tensor([1, 3, 5, 7, 9])

In [25]:
tens2[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])